### ISSUE TITLE
About WSDDN_pre_train model

### ISSUE THREAD

**Issue by Jngwl** [Sunarker/Collaborative-Learning-for-Weakly-Supervised-Object-Detection#11]
Hello,Thanks for sharing your great works again.
Recently, when I changed the `Pascal VOC2007` training set to my own training set (only 6 classes of pictures), I encountered a problem that the `class_score_net.bias` dimension did not match. 
Can you share how the `WSDDN` pre-training model was obtained?
Thank you very much!

**Comment by Sunarker** [comment]
One easy way to get this is training WSDDN by following the schedule in its original [paper](https://www.robots.ox.ac.uk/~vgg/publications/2016/Bilen16/bilen16.pdf). You can use the corresponding implementation of WSDDN in this project to train, save and reload.

**Comment by Sunarker** [comment]
Since you want to tailor this work to your scenario, I think you should be familiar with our code first. Then, it is easy for you to extract the corresponding code of WSDDN in this project, and rewrite an independent script to train the WSDDN.

**Comment by Jngwl** [comment]
> Since you want to tailor this work to your scenario, I think you should be familiar with our code first. Then, it is easy for you to extract the corresponding code of WSDDN in this project, and rewrite an independent script to train the WSDDN.

I get it, thank you very much

**Comment by DongSky** [comment]
I have a question. I tried this training framework with only imagenet pretrained model instead of wsddn pretrained model on voc2007 dataset, and the training setting is same to original code. However, the AP on strong branch dropped from 48.3(reported result) to 20.1(newly trained). Is WSDDN pretrained model essential for the initialization of WSCDN training framework?
